interface billsClientsDOM {
    bill: number,
    cards: cardsClientsDOM[],
}

interface cardsClientsDOM {
    viewCard: string,
    numberCard: number,
    personalFunds: number,
    funds: number,
    limit: number,
    expiryDate: string,
    isActive: boolean,
    currency: string,
}

const bills: billsClientsDOM[] = [
    {
        bill: 123451,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123451,
                personalFunds: 10000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            },
            {
                viewCard: 'credit',
                numberCard: 333123451,
                personalFunds: 223000.0,
                funds: 7000.0,
                limit: 7000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123452,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123452,
                personalFunds: 1000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            },
            {
                viewCard: 'credit',
                numberCard: 333123452,
                personalFunds: 0.0,
                funds: 3540.0,
                limit: 10000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123453,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123453,
                personalFunds: 103000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'USD',
            },
            {
                viewCard: 'credit',
                numberCard: 333123453,
                personalFunds: 23000.0,
                funds: 20000.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123454,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123454,
                personalFunds: 400.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2020-01-01',
                isActive: false,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123454,
                personalFunds: 235.0,
                funds: 6001.0,
                limit: 7000.0,
                expiryDate: '2020-01-01',
                isActive: false,
                currency: 'UAH',
            }],
    },
    {
        bill: 123455,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123455,
                personalFunds: 78000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'RUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123455,
                personalFunds: 7987.0,
                funds: 20000.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123456,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123456,
                personalFunds: 15000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'USD',
            },
            {
                viewCard: 'credit',
                numberCard: 333123456,
                personalFunds: 15.0,
                funds: 348.0,
                limit: 7000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123457,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123457,
                personalFunds: 10.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            },
            {
                viewCard: 'credit',
                numberCard: 333123457,
                personalFunds: 23928.0,
                funds: 7000.0,
                limit: 7000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123458,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123458,
                personalFunds: 90000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'USD',
            },
            {
                viewCard: 'credit',
                numberCard: 333123458,
                personalFunds: 23870.0,
                funds: 20000.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123459,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123459,
                personalFunds: 700.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2020-01-01',
                isActive: false,
                currency: 'UAH',
            },
            {
                viewCard: 'credit',
                numberCard: 333123459,
                personalFunds: 382883.0,
                funds: 465.0,
                limit: 20000.0,
                expiryDate: '2020-01-01',
                isActive: false,
                currency: 'UAH',
            }],
    },
    {
        bill: 123460,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123460,
                personalFunds: 1000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123460,
                personalFunds: 0.0,
                funds: 0.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123461,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123461,
                personalFunds: 90.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123461,
                personalFunds: 0.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2020-01-01',
                isActive: false,
                currency: 'UAH',
            }],
    },
    {
        bill: 123462,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123462,
                personalFunds: 900.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123462,
                personalFunds: 457.0,
                funds: 100.0,
                limit: 7000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123463,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123463,
                personalFunds: 10000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'USD',
            },
            {
                viewCard: 'credit',
                numberCard: 333123463,
                personalFunds: 127847.0,
                funds: 20000.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123464,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123464,
                personalFunds: 10000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123464,
                personalFunds: 348.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2020-01-01',
                isActive: false,
                currency: 'UAH',
            }],
    },
    {
        bill: 123465,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123465,
                personalFunds: 547321.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            },
            {
                viewCard: 'credit',
                numberCard: 333123465,
                personalFunds: 723000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123466,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123466,
                personalFunds: 100000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123466,
                personalFunds: 2321.0,
                funds: 23.0,
                limit: 5000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123467,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123467,
                personalFunds: 10.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'USD',
            },
            {
                viewCard: 'credit',
                numberCard: 333123467,
                personalFunds: 2394.0,
                funds: 14000.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123468,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123468,
                personalFunds: 1340.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'EUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123468,
                personalFunds: 749231.0,
                funds: 200000.0,
                limit: 200000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
    {
        bill: 123469,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123469,
                personalFunds: 10000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2019-01-01',
                isActive: false,
                currency: 'RUR',
            },
            {
                viewCard: 'credit',
                numberCard: 333123469,
                personalFunds: 29325.0,
                funds: 5000.0,
                limit: 7000.0,
                expiryDate: '2019-01-01',
                isActive: false,
                currency: 'UAH',
            }],
    },
    {
        bill: 123470,
        cards: [
            {
                viewCard: 'debit',
                numberCard: 222123470,
                personalFunds: 231000.0,
                funds: 0.0,
                limit: 0.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            },
            {
                viewCard: 'credit',
                numberCard: 333123470,
                personalFunds: 328837.0,
                funds: 20000.0,
                limit: 20000.0,
                expiryDate: '2025-01-01',
                isActive: true,
                currency: 'UAH',
            }],
    },
];