interface clientsBankDOM {
    id: number,
    surname: string,
    name: string,
    patronymic: string,
    isActive: boolean,
    registration: string,
    bill: number,
}

const clients: clientsBankDOM[] = [
    {
        id: 1,
        surname: 'Горелов',
        name: 'Игорь',
        patronymic: 'Андреевич',
        isActive: true,
        registration: '2017-05-29',
        bill: 123451,
    },
    {
        id: 2,
        surname: 'Стесненко',
        name: 'Света',
        patronymic: 'Петровна',
        isActive: false,
        registration: '2001-10-21',
        bill: 123452,
    },
    {
        id: 3,
        surname: 'Кушнир',
        name: 'Олег',
        patronymic: 'Сергеевич',
        isActive: true,
        registration: '2000-04-11',
        bill: 123453,
    },
    {
        id: 4,
        surname: 'Щупова',
        name: 'Елена',
        patronymic: 'Антоновна',
        isActive: false,
        registration: '2019-06-07',
        bill: 123454,
    },
    {
        id: 5,
        surname: 'Кисленко',
        name: 'Ольга',
        patronymic: 'Владимировна',
        isActive: true,
        registration: '2012-11-05',
        bill: 123455,
    },
    {
        id: 6,
        surname: 'Звездный',
        name: 'Петр',
        patronymic: 'Андреевич',
        isActive: true,
        registration: '2012-08-10',
        bill: 123456,
    },
    {
        id: 7,
        surname: 'Иствуд',
        name: 'Андрей',
        patronymic: 'Максимович',
        isActive: true,
        registration: '2016-03-15',
        bill: 123457,
    },
    {
        id: 8,
        surname: 'Красотка',
        name: 'Анастасия',
        patronymic: 'Антоновна',
        isActive: true,
        registration: '2013-12-17',
        bill: 123458,
    },
    {
        id: 9,
        surname: 'Шевцов',
        name: 'Игорь',
        patronymic: 'Степанович',
        isActive: false,
        registration: '1997-06-09',
        bill: 123459,
    },
    {
        id: 10,
        surname: 'Солодов',
        name: 'Максим',
        patronymic: 'Филлипович',
        isActive: true,
        registration: '2019-03-11',
        bill: 123460,
    },
    {
        id: 11,
        surname: 'Шикарный',
        name: 'Андрей',
        patronymic: 'Петрович',
        isActive: true,
        registration: '2018-05-15',
        bill: 123461,
    },
    {
        id: 12,
        surname: 'Красивый',
        name: 'Владимир',
        patronymic: 'Сергеевич',
        isActive: true,
        registration: '2003-12-21',
        bill: 123462,
    },
    {
        id: 13,
        surname: 'Гордый',
        name: 'Андрей',
        patronymic: 'Степанович',
        isActive: true,
        registration: '2001-07-16',
        bill: 123463,
    },
    {
        id: 14,
        surname: 'Светлая',
        name: 'Нина',
        patronymic: 'Игоревна',
        isActive: true,
        registration: '2000-07-03',
        bill: 123464,
    },
    {
        id: 15,
        surname: 'Блонди',
        name: 'Валентина',
        patronymic: 'Федоровна',
        isActive: true,
        registration: '2012-09-04',
        bill: 123465,
    },
    {
        id: 16,
        surname: 'Севастьянов',
        name: 'Артем',
        patronymic: 'Олегович',
        isActive: true,
        registration: '2016-03-12',
        bill: 123466,
    },
    {
        id: 17,
        surname: 'Орешек',
        name: 'Света',
        patronymic: 'Сергеевна',
        isActive: true,
        registration: '2019-05-22',
        bill: 123467,
    },
    {
        id: 18,
        surname: 'Крепкий',
        name: 'Андрей',
        patronymic: 'Петрович',
        isActive: true,
        registration: '2007-09-09',
        bill: 123468,
    },
    {
        id: 19,
        surname: 'Светский',
        name: 'Максим',
        patronymic: 'Васильевич',
        isActive: false,
        registration: '2015-11-04',
        bill: 123469,
    },
    {
        id: 20,
        surname: 'Гога',
        name: 'Вячеслав',
        patronymic: 'Сергеевич',
        isActive: true,
        registration: '2013-02-01',
        bill: 123470,
    },

];
